# Generated by Django 6.0 on 2025-12-30 18:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الدورة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'دورة',
                'verbose_name_plural': 'الدورات',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('university_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='رقم القيد الجامعي')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الخماسي')),
                ('jihad_name', models.CharField(max_length=100, verbose_name='الاسم الجهادي')),
                ('birth_year', models.IntegerField(verbose_name='سنة الميلاد')),
                ('governorate', models.CharField(max_length=100, verbose_name='المحافظة')),
                ('directorate', models.CharField(max_length=100, verbose_name='المديرية')),
                ('isolation', models.CharField(max_length=100, verbose_name='العزلة')),
                ('village', models.CharField(max_length=100, verbose_name='القرية')),
                ('specialization', models.CharField(max_length=200, verbose_name='التخصص')),
                ('affiliation', models.CharField(max_length=200, verbose_name='التبعية')),
                ('contact_number', models.CharField(max_length=20, verbose_name='رقم التواصل')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإدخال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='dept.course', verbose_name='الدورة')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أدخل بواسطة')),
            ],
            options={
                'verbose_name': 'مشارك',
                'verbose_name_plural': 'المشاركون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'مستخدم عادي'), ('admin', 'مسؤول')], default='user', max_length=20, verbose_name='الصلاحية')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
    ]
