# Generated by Django 6.0 on 2026-01-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='university_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='رقم العسكري '),
        ),
    ]
